name: Scan Dockerfile

on:
  push:
    paths:
      - "docker/php/Dockerfile"
  pull_request:
    paths:
      - "docker/php/Dockerfile"
  workflow_dispatch:

jobs:
  scan:
    name: Scan Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "docker/php/Dockerfile"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
